# Generated by Django 5.1.6 on 2025-02-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harit_aahar_app", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
