name: Deploy Django and React to EC2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            #!/bin/bash
            set -e

            echo "Running on host: $(hostname)"
            REMOTE_PROJECT_DIR="/home/ubuntu/Harit_Aahar"

            #### ✅ Ensure the project directory exists ####
            if [ ! -d "$REMOTE_PROJECT_DIR" ]; then
              echo "Project directory does not exist. Cloning fresh repository..."
              git clone --branch deploy --depth 1 https://github.com/kanhaiyap/Harit_Aahar.git "$REMOTE_PROJECT_DIR"
            else
              echo "Project directory exists. Pulling latest changes..."
              cd "$REMOTE_PROJECT_DIR"
              git reset --hard  # Prevent conflicts
              git pull origin deploy || { echo "Git pull failed!"; exit 1; }
            fi

            echo "Changing ownership of $REMOTE_PROJECT_DIR to ubuntu..."
            sudo chown -R ubuntu:ubuntu "$REMOTE_PROJECT_DIR"

            #### ✅ Install & Start Redis ####
            echo "Checking if Redis is installed..."
            if ! command -v redis-server &> /dev/null
            then
                echo "Redis not found. Installing Redis..."
                sudo apt update
                sudo apt install -y redis-server
            fi

            echo "Starting Redis service..."
            sudo systemctl start redis
            sudo systemctl enable redis
            sudo systemctl status redis --no-pager || { echo "Redis failed!"; exit 1; }

            #### Deploy Django Backend ####
            echo "Changing directory to '$REMOTE_PROJECT_DIR/backend'..."
            cd backend || { echo "Backend directory not found!"; exit 1; }

            # Ensure virtual environment exists
            if [ ! -d "venv" ]; then
              echo "Virtual environment not found. Creating one..."
              python3 -m venv venv
            fi

            echo "Activating virtual environment..."
            source venv/bin/activate

            echo "Installing backend dependencies..."
            pip install -r requirements.txt

            echo "Running Django migrations..."
            python manage.py migrate

            echo "Collecting static files..."
            python manage.py collectstatic --noinput

            echo "Restarting Gunicorn service..."
            sudo systemctl restart gunicorn

            #### Deploy React Frontend ####
            echo "Changing directory to '$REMOTE_PROJECT_DIR/frontend'..."
            cd ../frontend || { echo "Frontend directory not found!"; exit 1; }

            echo "Installing frontend dependencies..."
            npm install

            echo "Building React application..."
            npm run build
            
            echo "Copying React build to Nginx directory..."
            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/

            echo "Restarting Nginx..."
            sudo systemctl restart nginx
            sudo systemctl status nginx --no-pager || { echo "Nginx failed!"; exit 1; }

            # After "npm run build"
            echo "Starting frontend using systemctl..."
            sudo systemctl restart react-frontend

            echo "Deployment successful!"
