name: Deploy Django and React to EC2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            #!/bin/bash
            set -e

            echo "Running on host: $(hostname)"
            REMOTE_PROJECT_DIR="/home/ubuntu/Harit_Aahar"

            echo "Deleting existing project directory (if it exists)..."
            sudo rm -rf "$REMOTE_PROJECT_DIR"

            echo "Cloning repository (deploy branch) into $REMOTE_PROJECT_DIR..."
            git clone --branch deploy --depth 1 https://github.com/kanhaiyap/Harit_Aahar.git "$REMOTE_PROJECT_DIR" || { echo "Clone failed!"; exit 1; }

            echo "Changing ownership of $REMOTE_PROJECT_DIR to ubuntu..."
            sudo chown -R ubuntu:ubuntu "$REMOTE_PROJECT_DIR"

            echo "Changing directory to '$REMOTE_PROJECT_DIR'..."
            cd "$REMOTE_PROJECT_DIR" || { echo "Directory not found!"; exit 1; }

            echo "Reloading and starting Docker service..."
            sudo systemctl daemon-reload
            sudo systemctl start docker
            sudo usermod -aG docker ubuntu

            echo "Creating Docker network 'harit_network' if it doesn't exist..."
            sudo docker network inspect harit_network >/dev/null 2>&1 || sudo docker network create harit_network

            echo "Building frontend Docker image on EC2..."
            docker build --platform linux/amd64 -t harit-frontend:latest ./frontend

            echo "Building backend Docker image on EC2..."
            docker build --platform linux/amd64 -t harit-backend:latest ./backend

            echo "Removing existing containers (if any)..."
            sudo docker rm -f harit_frontend_container harit_backend_container 2>/dev/null || true

            echo "Running backend container..."
            sudo docker run -d --name harit_backend_container \
              --network harit_network --network-alias backend \
              -p 8000:8000 harit-backend:latest

            echo "Running frontend container..."
            sudo docker run -d --name harit_frontend_container \
              --network harit_network \
              -p 8080:80 harit-frontend:latest

            echo "Listing web root contents in the frontend container for verification..."
            sudo docker exec harit_frontend_container ls -l /usr/share/nginx/html

            echo "Deployment successful!"
